# Generated by Django 5.1.5 on 2025-02-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/profile-user.png', upload_to='profile_pics/'),
        ),
    ]
